# Book settings
title: Sok-1303 
author: Anita Michalsen, Daniel Nikolai Johannessen og Daniel Fabio Groth
logo: assets/img/py.png


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off
  allow_errors: true
  # exclude_patterns:
  #   - 'notebooks/00/intro.ipynb'
  #   - 'notebooks/01/introduksjon.ipynb'
  #   - 'notebooks/10/simulering.ipynb'

sphinx:
  config:
    nb_kernel_rgx_aliases:
      ".*": "python3"
    html_theme: "sphinx_book_theme"
    html_show_copyright: false


# Information about where the book exists on the web
repository:
  url: https://github.com/Danieljoha/Bed-1304-ressursside  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    # Defaults here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image
    - amsmath
    - dollarmath



# execute:
#   timeout: -1 # Disable timeouts for executing notebooks




